### ISSUE TITLE
Ticket expired. Getting new one.

### ISSUE THREAD

**Issue by redfoxcrypto** [Matthew17-21/Newegg-Shuffle#10]
Unable to create Newegg accounts. After solving captcha, error is "Ticket expired. Getting new one." Was working fine last night, but now haven't been able to create an account successfully.

<img width="341" alt="Screen Shot 2021-06-13 at 8 54 08 AM" src="https://user-images.githubusercontent.com/85831732/121808066-ee125580-cc24-11eb-9ce0-edc3cb13e5f9.png">

**Comment by Matthew17-21** [comment]
Ticket expired is semi normal... it happens when the captcha take too long to solve admins some time has passed. 

Either restart the entire program or just keep it running until it can solve the captcha quick enough.

**Comment by redfoxcrypto** [comment]
Thanks for the quick reply. Last night I was able to create 25 accounts in 30 minutes. Today it's been running for 2 hours without a successful account creation. Same proxies and same captcha provider (capmonster). I also tried anti-captcha but same issue. Tried restarting as well.

**Comment by Matthew17-21** [comment]
Just tried it out myself and no issues. If you have been using the same static IP, try switching them out. 
![Genning](https://i.imgur.com/szkfbFI.png)
