### ISSUE TITLE
Error Getting Raffle Items

### ISSUE THREAD

**Issue by mew32jfd** [Matthew17-21/Newegg-Shuffle#12]
Program was working until recently an error in given when attempting too fetch raffle items  

Python(3.8.10)

Expecting property name enclosed in double quotes: line 1 column 3 (char 2)
[ERROR GETTING RAFFLES]

--This line of code throws error 
raffle_products =  json.loads(re.findall(r"{.+[:,].+}", res.text)[1].split("</script>")[0])

raffles.py

**Comment by HuskyCodez** [comment]
> Program was working until recently an error in given when attempting too fetch raffle items
> 
> Python(3.8.10)
> 
> Expecting property name enclosed in double quotes: line 1 column 3 (char 2) [ERROR GETTING RAFFLES]
> 
> --This line of code throws error raffle_products = json.loads(re.findall(r"{.+[:,].+}", res.text)[1].split("</script>")[0])
> 
> raffles.py

probably because the returned value did not match a json type

**Comment by Matthew17-21** [comment]
Better late than never?

[Fixed with version 1.1.3](https://github.com/Matthew17-21/Newegg-Shuffle/releases/tag/1.1.3)
