### ISSUE TITLE
SSL Error Line 82

### ISSUE THREAD

**Issue by coreyjs3308** [Matthew17-21/Newegg-Shuffle#14]
I'm getting Error on line 82 SSLError HTTPSConnectionPool(host='www.newegg.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)')))

Running on Windows.

**Comment by Matthew17-21** [comment]
This doesn't directly deal with this repo but I'll try to quickly help out before closing. What version of `requests` are you running? What Python version?

Some articles that can potentially resolve the issue:
[Possible solution 1](https://flutterq.com/ssl-wrong_version_number-on-python-request/)
