### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by xBlackPoison357x** [Matthew17-21/Newegg-Shuffle#2]
`Traceback (most recent call last):
  File "C:\Newegg-Shuffle-main\main.py", line 19, in <module>
    with open("./data/settings.json") as settingsFile:
FileNotFoundError: [Errno 2] No such file or directory: './data/settings.json'`

Thank you for your help in solving the previous issue. I got it running and then i got this one that seems like its not seeing the settings file but its at "C:\Newegg-Shuffle-main\data\settings.json"

**Comment by Matthew17-21** [comment]
Glad you got the last issue solved.

As far as this issue goes, it seems that the way I implemented it to get the path's isn't sufficient for different OS'. I'll change the code a bit so this can be solved. I'll have an update for this, plus add little other features sometime this week.

 I'll keep this issue open as a reminder.

**Comment by Matthew17-21** [comment]
Hi!

Error should be fixed. Check [new update.](https://github.com/Matthew17-21/Newegg-Shuffle/releases/tag/1.1.0)

Thank you
