### ISSUE TITLE
Captcha V2

### ISSUE THREAD

**Issue by thebetauser** [Matthew17-21/Newegg-Shuffle#3]
This line should be set to "v2" not "v3" otherwise setting "v2" in the settings.json results in a `UnboundLocalError: local variable 'sitekey' referenced before assignment` error when executing the program

https://github.com/Matthew17-21/Newegg-Shuffle/blob/a973de121d45d839464a9bb83665c9d633afa9b8/main.py#L38

**Comment by Matthew17-21** [comment]
Yikes. Can't believe I didn't catch that. 

Just fixed error and will push it out tonight alongside the new update. 

Thank you
