### ISSUE TITLE
Discord Webhook

### ISSUE THREAD

**Issue by collinmyers** [Matthew17-21/Newegg-Shuffle#7]
Add Discord Webhook when shuffle is successfully entered as an option that can be used

**Comment by Matthew17-21** [comment]
I can def add... You don't think it'll be too many webhooks tho? Would webhooks also be for successfully creating accounts> Or just on entering?

**Comment by collinmyers** [comment]
Could make it an option be turn on and off w/ a true or false in the settings file. I would personally use it. And possibly both

**Comment by Matthew17-21** [comment]
Thanks for the request. I think I'll go thru with adding it... I'll see to adding it by Wednesday, end of the week the latest. Stay tuned for the next update.

Thanks again
