### ISSUE TITLE
Submitting Entries

### ISSUE THREAD

**Issue by collinmyers** [Matthew17-21/Newegg-Shuffle#8]
I keep having this issue where so many accounts get submitted then no more are done after this, I have tried switching between v2 and v3, as well as changing from 2captcha to capmonster.
![image](https://user-images.githubusercontent.com/51715099/121222744-cdc54e00-c854-11eb-8973-bbb272181a43.png)

**Comment by Matthew17-21** [comment]
The ones that say `UnAccess. Stopping.` stop those tasks entirely. For example, if you run 2 tasks and 1 of them gets hit with the `UnAccess. Stopping.`, only run 1 task will run from there on.  I did this as kinda a safety policy... I didn't want any more accounts to run into the same problem (incase it flags it or anything).

`UnAccess. Stopping.` could mean several things:
- Account is now logged out 
- Raffle not live / done 
- A item in the raffle can't be entered

Theres lots of reasons, but Newegg doesn't explicitly tell you why it doesn't allow that entry, so I just don't risk it.

**Comment by krashchiy** [comment]
Is there a way to relogin for logged out accounts with the bot? Or do we need to manually replace all cookies in 'successfully created accounts.log' for such accounts?

**Comment by Matthew17-21** [comment]
When I used to run it never happened to me so there was no need for a solution for that. 

But the way I see it there are 2 ways:
1) Manually replace the sessions in the log file
2A) Make a program to attempt to login WITH THE OLD SESSION (this could help prevent the verification code)
2B) Make a program to login as normal (This might send a verification code to your email)
